=== SebaNLee/itba-github/20242Q/xml/tp02/ej1.dtd
<!ELEMENT emails (email*)>
<!ELEMENT email (date, header, subject, body)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT header (from, to)>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT body (#PCDATA)>
<!ELEMENT from (name, address)>
<!ELEMENT to (name, address)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>

<!ATTLIST date format CDATA #REQUIRED>
<!ATTLIST name format CDATA #REQUIRED>
<!ATTLIST subject maxLengthValue CDATA #REQUIRED>

=== SebaNLee/itba-github/20242Q/xml/tp02/ej1.xml
<?xml version="1.0"?>
<!-- el documento se llamaría emails.xml -->

<!DOCTYPE emails SYSTEM "ej1.dtd">

<emails>
    <email>
        <date format="YYYY-MM-DD"></date>

        <header>
            <from>
                <name format="nombre, apellido"></name>
                <address></address>
            </from>
            <to>
                <name format="nombre, apellido"></name>
                <address></address>
            </to>

        </header>

        <subject maxLengthValue="256">

        </subject>
        
        <body>

        </body>
    </email>

    <!-- y se copiaría email 2 veces más -->

</emails>

<!-- si bien puedo corroborar que el usuario ponga al codear etiquetas y atributos no puedo valirdar el qué pone -->
<!-- java dom.Writer -v ej1.xml -->
