<?xml version="1.0"?>
<!-- el documento se llamaría emails.xml -->

<!DOCTYPE emails 
[<!ELEMENT emails (email*)>
 <!ELEMENT email (date, header, subject, body)>
 <!ELEMENT date (#PCDATA)>
 <!ELEMENT header (from, to+)> <!-- agregado el + en to -->
 <!ELEMENT subject (#PCDATA)>
 <!ELEMENT body (#PCDATA)>
 <!ELEMENT from (name, address)>
 <!ELEMENT to (name, address)> 
 <!ELEMENT name (#PCDATA)>
 <!ELEMENT address (#PCDATA)>

 <!ATTLIST date format CDATA #REQUIRED>
 <!ATTLIST name format CDATA #REQUIRED>
 <!ATTLIST subject maxLengthValue CDATA #REQUIRED>

 <!ATTLIST email id_email ID #IMPLIED>
 <!ATTLIST email id_answer IDREF #IMPLIED>

 <!ATTLIST header encoding (UTF-8|UTF-16|ISO-8859-1) "UTF-8"> <!-- agrego encoding, default UTF-8 -->
]>



<emails>
    <email id_email="AA111">
        <date format="YYYY-MM-DD"></date>

        <header>
            <from>
                <name format="nombre, apellido"></name>
                <address></address>
            </from>
            <to>
                <name format="nombre, apellido"></name>
                <address></address>
            </to>
            <to>
                <name format="nombre, apellido"></name>
                <address></address>
            </to>
            <to>
                <name format="nombre, apellido"></name>
                <address></address>
            </to>
            <to>
                <name format="nombre, apellido"></name>
                <address></address>
            </to>

        </header>

        <!-- CODIGOSEG1, si agrego este código de seguridad me salta error, lo comento -->
        
        <subject maxLengthValue="256">

        </subject>
        
        <body>

        </body>
    </email>

    <email id_answer="AA111">
        <date format="YYYY-MM-DD"></date>

        <header>
            <from>
                <name format="nombre, apellido"></name>
                <address></address>
            </from>
            <to>
                <name format="nombre, apellido"></name>
                <address></address>
            </to>

        </header>

        <subject maxLengthValue="256">

        </subject>
        
        <body>

        </body>
    </email>

    <!-- y se copiaría email 2 veces más -->

</emails>

<!-- si bien puedo corroborar que el usuario ponga al codear etiquetas y atributos no puedo valirdar el qué pone -->
<!-- java dom.Writer -v ej3.xml -->

 